version: '3.2'

services:

  # Developers Italia Onboarding
  developers-italia-onboarding:
    container_name: developers-italia-onboarding
    image: italia/developers-italia-onboarding:dockerize
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - demo-data:/private/data

volumes:
  demo-data:
