# Javascript Node CircleCI 2.1 configuration file
## Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ for more details

references:
  working_directory: /tmp/onboarding

  load_image: &load_image
    docker:
      - image: circleci/node:lts

  install_dependencies: &install_dependencies
    run:
      name: npm-install
      command: |
        npm install

  lint: &lint
    run:
      name: lint
      command: |
        npm run lint

version: 2
jobs:
  test:
    <<: *load_image
    steps:
      - checkout
      - << : *install_dependencies
      - run: npm run test
      - << : *lint

workflows:
  version: 2
  # For any branch other than master,
  # run CI tests at each commit
  on-commit-test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
